[project]
name = "bluesky-feed-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "atproto>=0.0.55",
    "flask>=3.0.3",
    "peewee>=3.17.8",
    "python-dotenv>=1.0.1",
]
